### ISSUE TITLE
Apr - May timeline

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-pilot2#10]
first version of teal https://genentech.shinyapps.io/FDA-app/

next steps: @wangh107 , Tad to
- merge @hoppanda 's PR on efficacy table
- merge @mstackhouse / @elimillera  's update on primary table
- merge @rpodcast 's md front page

Apr 7: new deployment on shinyapps.io, execution team reveiw

Apr 21: larger team review (shinyapp.io and ADRG?)

May: adjudication and implement golem

**Comment by mstackhouse** [comment]
@lengning  updates are all taking place in this repository, correct?

**Comment by lengning** [comment]
@mstackhouse yes please feel free to start a new pr of this repo

**Comment by elimillera** [comment]
Hey @lengning The PR linked here has the changes. Thanks!
