### ISSUE TITLE
Consider adding Dockerfile

### ISSUE THREAD

**Issue by parmsam-pfizer** [RConsortium/submissions-pilot2#21]

**Comment by rpodcast** [comment]
A great suggestion. With the app being converted to the `{golem}` infrastructure, we can easily generate a Dockerfile.

**Comment by parmsam-pfizer** [comment]
Something to note is that there was a question about Docker at yesterday's R Adoption Series webinar on Using R In Regulatory Review (timestamped link here: https://youtu.be/dtdd_jc1ybw?t=3958). It seems that attempts so far to use Docker at FDA have not been successful due to approved Docker version issues. There also seem to be concerns about Docker's subscription model, so they are considering other solutions like Podman.

**Comment by parmsam-pfizer** [comment]
Going with Podman instead.
