### ISSUE TITLE
In ADRG: Document additional R packages used in shiny app

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-pilot2#23]
fill in the table in appendix 2 of [ADRG](https://docs.google.com/document/d/1Dvzkcvr5F2ivy02NfDsheZdMqmdqcXjk9-vToR0N2ZI/edit#heading=h.3broi1fmyqbi)
Information needed
- pkg name
- version
- description

**Comment by rpodcast** [comment]
I'm able to dynamically generate the package list using a modified version of the snippet in the `adrg-prepare.Rmd` vignette. I'll commit the final version of the vignette to the repo but here is the snippet:

```r
pkg <- desc::desc_get_deps() %>%
  filter(type == "Imports") %>%
  pull(package)

# custom code to obtain package descriptions
pkg_desc <- tibble::tibble(Package = pkg) %>%
  mutate(Version = purrr::map_chr(Package, ~utils::packageDescription(.x, fields = "Version"))) %>%
  mutate(Description = purrr::map_chr(Package, ~utils::packageDescription(.x, fields = "Description"))) %>%
  arrange(Package)

pkg_desc
```
