### ISSUE TITLE
In ADRG: installation guidance of shiny app

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-pilot2#24]
appendix 2 in [ADRG](https://docs.google.com/document/d/1Dvzkcvr5F2ivy02NfDsheZdMqmdqcXjk9-vToR0N2ZI/edit#heading=h.3broi1fmyqbi)

**Comment by rpodcast** [comment]
I've verified that with a few modifications of the pilot 1 procedure, I am able to successfully bundle the application with `pkglite` and then successfully unpack & install the package source into the renv library. The app can then be executed with `pilot2wrappers::run_app()`.
