### ISSUE TITLE
put pilot2 files into eCTD structure

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-pilot2#29]
https://github.com/RConsortium/submissions-pilot2-to-fda

**Comment by rpodcast** [comment]
As I finalized the ectd files for Pilot 2, I want to make sure I'm aligned with the scope. Should we include the previous ectd files from pilot 1 within the pilot 2 version, or should we include only what is necessary to install and execute the Shiny application in the pilot 2 ectd files?

**Comment by lengning** [comment]
I would prefer the latter (only files needed for pilot 2), otherwise it may be too overwhelming? I know in adrg we also included the static TLF info, perhaps in adrg we can make it clear that those files are included in the pilot 1 esub pkg (and link to our pilot1-to-fda repo?)

**Comment by rpodcast** [comment]
Thanks @lengning , I've been working under that assumption as well. I'll make sure the ADRG for pilot 2 is clear about the included files.
