### ISSUE TITLE
Using `{golem}` for package infrastructure

### ISSUE THREAD

**Issue by rpodcast** [RConsortium/submissions-pilot2#5]
This application is coming along really well, and a lot of foundational pieces are in place. One improvement we could make to ensure the application is even easier to run and develop is to wrap the app files into a slightly revised package based on [`{golem}`](https://github.com/ThinkR-open/golem). I used `golem` in my Shiny application sent to the FDA for the CID Pilot, and it led to a high-quality application bundle that was also easy to run for the reviewers. I would be glad to take the lead on this, but wanted to make sure there weren't any concerns before carrying out that work.

**Comment by elong0527** [comment]
I am supporting this strategy 👍

**Comment by rpodcast** [comment]
My in-progress notes of the migration for updates/discussion:

# Migration to golem notes

## Installing TEAL into `renv`

* A custom repository is needed to install the current version of TEAL, as documented at [insightsengineering/depository](https://github.com/insightsengineering/depository).
* To add this into the repository list that `{renv}` uses for installing packages, run following snippet (only needs to be done once):

```r
lock <- renv:::lockfile("renv.lock")
lock$repos(
  CRAN = "https://packagemanager.rstudio.com/cran/2022-02-01", 
  TEAL = "https://insightsengineering.github.io/depository/2022_06_09"
)
lock$write("renv.lock")
```

Restart your current R session, and then install TEAL with `renv::install("teal")`

## Running example app (without golem)

* The `{reactable}` package was not installed, so I installed with `renv::install("reactable")`
* Same with `{markdown}`
* Running the app in VS-Code: `withr::with_dir("inst/shiny/app", shiny::runApp())`

## Repo structure

* The current structure is an R package called `pilot2wrappers`. My plan is to keep this same name but convert the overall structure to resemble a `golem` app. We should still be able to keep the other pieces like the `pkgdown` site, etc

## Begin Migration

* [x] Install `golem` into the package library: `renv::install("golem")`
* [x] Create the golem-version of directory structure in a tmp location and begin manually copying and modifying boilerplate files in the current repo dir. **Needs to run in RStudio due to integration with `rstudioapi`**

Within a terminal shell: `mkdir -p /tmp/golemtmp/pilot2wrappers`

Within R console:

```r
golem::create_golem("/tmp/golemtmp/pilot2wrappers, open = FALSE)
```

* [x] Copy over `dev` folder (no modifications needed for now)
* [x] Copy over `inst/app` dir into existing `inst` dir
* [x] Update `dev/02_dev.R` to declare packages needed for the app. Inspect list of packages loaded in the current draft of the app that uses teal inside `inst/shiny/app/app.R`
* [x] Migrate golem-specific files created in the `R` dir to this repo's existing `R` dir
* [x] Migrate supporting R scripts for draft teal app in `inst/shiny/app/`(such as `tm_*.R`) to `R` directory

## Observations / Questions

* Teal is amazing!
* It seems like to get teal to fit into golem, we need to supply the ui and server objects as produced by `teal::init()` into the `run_app` function golem uses in `R/run_app.R`. Traditionally, a golem app expects scripts like `app_ui.R` and `app_server.R` to serve up the UI and server-side code as objects supplied in a traditional `shiny::runApp()` call
* The teal app imports the CDISC data sets via haven as those are used in the definition of the app. Can we put the `adam` data set contents inside a `data-raw` directory and import them with traditional means, or simply throw the `adam` directory into `inst/app` and reference them in there?
* Another idea: We create a separate script in the `R` dir that runs functions like the `app.R` of the TEAL example, and then modify `run_app` to call that function and supply the UI and server objects as appropriate

**Comment by rpodcast** [comment]
I have a first draft of the golem-version of the app ready for review. The app is on the `golem_app` branch [here](https://github.com/RConsortium/submissions-pilot2/tree/golem_app).  I will do some additional testing on other operating systems and flesh out the remaining bits of documentation.

**Comment by lengning** [comment]
thanks a lot @rpodcast ! I was able to rerun the app locally :) 
seems `inst/app/docs/about.md` may be missing?
I will also add several issues for the to-do tasks

**Comment by wangh107** [comment]
> thanks a lot @rpodcast ! I was able to rerun the app locally :) seems `inst/app/docs/about.md` may be missing? I will also add several issues for the to-do tasks

It might be in Eric's local. Currently the`.gitignore` ignores the changes in any folder named `docs` so people won't be aware of the changes happening regarding `docs`.  We need to update the `.gitignore` and commit the `inst/app/docs/about.md`. 

My observation: To deploy it to shinyapps.io, `markdown` dependency needs to be added in `pilot2wrappers` package `DESCRIPTION` file to be included in `renv` lock file.  
After these minor updates, I'm able to publish it to my shinyapps.io account. 🚀

**Comment by rpodcast** [comment]
The application is now constructed with `{golem}` per the recent PR #27 . I will open a separate issue for testing feedback.
