### ISSUE TITLE
Format Suggestion: KM plot

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-pilot2#7]
Based on https://genentech.shinyapps.io/FDA-app/, below are minor format suggestions:

1. Move legend to the bottom 
2. Put date and time stamp as a footnote 
3. Using "Month" as time unit 
4. Clarify the shaded area is 95% CI in the footnote?
5. Y-axis: change unit to (%) 
6. Y-axis: Survival Probability (%)  
7. X-axis: Time (Months)
8. legend title: Group 
9. legend value: remove "TRT01A="

**Comment by wangh107** [comment]
An updated KM plot will look like the following:
Didn't find a way to address item 8 & 9 from `visR` package. 
<img width="1099" alt="Screen Shot 2022-04-20 at 10 29 00 PM" src="https://user-images.githubusercontent.com/30063353/164382740-7d2f197c-d5fb-4fd4-861f-c0acfa438127.png">
